#! /usr/bin/env zsh

# Exit immediately if any command returns non-zero status
# https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin
set -e

./venv/bin/python -m unittest discover --start-directory ./tests

./venv/bin/black --check --diff --config ./.github/config/pyproject.toml .

./venv/bin/pylint \
    --rcfile ./.github/config/pylintrc \
    --ignore=manage.py \
    $(git ls-files '*.py')

./venv/bin/mypy --config-file ./.github/config/mypy.ini mysite/mysite

./venv/bin/isort --diff --check-only .
