name: Python

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements_dev.txt

      - name: Lint with Black
        uses: psf/black@stable
        with:
          options: '--check --diff --config ./.github/config/pyproject.toml'
          src: '.'

      - name: Lint with Pylint
        run: pylint --rcfile ./.github/config/pylintrc mysite/mysite

      - name: Check with Mypy
        run: mypy --config-file ./.github/config/mypy.ini mysite/mysite

      - name: Check with isort
        uses: isort/isort-action@master
